import React from 'react';
import useScrollToHash from '../components/useScrollToHash';

import ProjetButton from '../components/ProjetButton';
import ProjetDetail from '../components/ProjetDetail';


function Projets() {
  useScrollToHash();
  return (
    <div>
      <a id='button-remonter' href='#'>
        <img src="../../fleche.png" alt="" />
      </a>
      <ProjetButton />
      <div id="annee1" className='projets-section'>
        <h1>1ère année</h1>
        <ProjetDetail id="projet-detail-1" title="Projet 1" txt="Dans ce projet, j'avais pour but de réaliser un jeu de Puissance 4 en langage C, qui se joue entièrement dans le terminal en utilisant les touches du clavier. Malgré les difficultés rencontrés en cours de route, j'ai réussi à terminer ce projet avec succès, ce qui m'a permis de consolider mes connaissances en C et de développer mes compétences en développement de jeux." media="../../dl/sae101.mp4" dlDossier="../../dl/Projet_BUT_semestre1_1.zip" langages={['C']} lienCompetence=" Lié à la competence 1"/>
        <ProjetDetail id="projet-detail-2" title="Projet 2" txt="Ce projet est la suite de celui ci dessus, la consigne était de créer un 'bot' pour pouvoir jouer seul au puissance 4 contre le programme que nous avons créé en binôme." media="../../sae_102/sae102.mp4" dlDossier="../../dl/Projet_BUT_semestre1_2.zip" langages={['C']} lienCompetence=" Lié à la competence 2"/>
        <ProjetDetail id="projet-detail-3" title="Projet 3" txt="Durant ce projet, nous avons dû utiliser Docker pour génération des PDF à partir d'un ensemble de fichiers bruts. La consigne qui nous a été donnée était claire : produire plusieurs PDF à partir de ce lot de fichiers, puis générer une unique archive compressée en tar.gz contenant tous les PDF générés. Travaillant en groupe de 4, nous avons collaboré pour mener à bien ce projet. Pour plus de détails et d'informations sur ce projet, je vous invite à vous référer au sujet qui nous a été fourni" media="../../sae_103/sae_103_1.png" dlDossier="../../dl/Projet_BUT_semestre1_3.zip" langages={['HTML', 'CSS', 'PHP', 'Docker']} lienCompetence=" Lié à la competence 3."/>
        <ProjetDetail id="projet-detail-4" title="Projet 4" txt="Pour ce projet réalisé en binôme, nous sommes partis d'une situation professionnelle fictive pour une application d'un festival de musique. Dans un premier temps, nous avons analysé les besoins et les contraintes pour en déduire un schéma UML. Ce schéma nous a servi de guide pour traduire les différentes tables et relations en SQL." media="../../sae_104/sae_104.png" dlDossier="../../dl/Projet_BUT_semestre1_4.zip" langages={[]} lienCompetence=" Lié à la competence 4."/>
        <ProjetDetail id="projet-detail-5" title="Projet 5" txt="Dans le cadre de notre projet de recueil des besoins, nous devions créer un site internet en suivant un processus bien défini. Par groupe de 4, nous avons entamé notre travail en nous concentrant sur l'arborescence du site, en définissant la structure et l'organisation des différentes pages. Ensuite, nous avons travaillé sur la charte graphique, en choisissant les couleurs, les typographies et les éléments visuels qui représenteraient au mieux notre projet. Une fois la charte graphique approuvée, nous avons procédé au maquettage, en concevant des prototypes visuels pour chaque page afin d'avoir une idée précise de l'apparence finale du site . Enfin, j'ai pris en charge la programmation de la page d'accueil et j'ai réalisé l'intégralité du CSS du site, en veillant à ce que le design soit cohérent et attrayant." media="../../sae_105/sae_105_1.png" dlDossier="../../dl/Projet_BUT_semestre1_5.zip" langages={[]} lienCompetence=" Lié à la competence 5."/>
        <ProjetDetail id="projet-detail-6" title="Projet 6" txt="Nous avons entrepris un projet au cours duquel nous devions sélectionner une entreprise à étudier et nous avons décidé de nous concentrer sur LEGO. Pour commencer, nous avons créé un tableau détaillé mettant en évidence les caractéristiques de cette organisation emblématique. Ensuite, nous avons procédé à un diagnostic externe complet de l'entreprise, en analysant ses opportunités et ses menaces. Ensuite lors de notre première soutenance, où nous avons exposé les principales informations sur l'entreprise, telles que son histoire, sa mission et ses produits. De plus, nous avons partagé les outils de groupe que nous avons utilisés pour mener à bien notre projet. Lors de notre deuxième soutenance, nous avons abordé les actions spécifiques que LEGO a mit en place pour améliorer leur empreinte numérique, leur responsabilité sociale et leur impact environnemental." media="../../sae_106/sae_106_1.png" dlDossier="../../dl/Projet_BUT_semestre1_6.zip" langages={[]} lienCompetence=" Lié à la competence 6."/>
      </div>
      <div id="annee2" className='projets-section'>
        <h1>2ème année</h1>
        <ProjetDetail id="projet-detail-7" title="Projet 1" txt="Par groupe de 3 il nous était demandé de développer un lot de fonctionnalités d'une application Java à partir d'un document SEL rédigé lors de la gestion du projet." media="../../sae_201/sae_201.png" dlDossier="../../dl/Projet_BUT_semestre1_1.zip" langages={['JavaFx']} lienCompetence=" Lié à la competence 1."/>
        <ProjetDetail id="projet-detail-8" title="Projet 2" txt="Notre mission était de résoudre le problème du cavalier donc le cavalier doit parcourir toutes les cases de l'échiquier sans passer 2 fois par la même. Ce projet a été réalisé en Python." media="../../sae_202/sae_202_1.png" dlDossier="../../dl/Projet_BUT_semestre2_2.zip" langages={[]} lienCompetence=" Lié à la competence 2."/>
        <ProjetDetail id="projet-detail-9" title="Projet 3" txt="Pour ce projet notre mission requiert l'installation et la configuration des services nécessaires au développement d'un site web. En effet, un site Web seul ne suffit pas, il lui faut à minima des modules supplémentaires tels qu’un langage de programmation et une base de données pour générer du contenu dynamique et personnalisé pour différents utilisateurs de différents profils. Dans notre cas, nous avons manipuler tout cela sous un environnement Linux avec un serveur Web de type Apache, une base de données de type MySQL, et le langage  PHP." media="../../sae_203/poulet2.webp" dlDossier="../../dl/Projet_BUT_semestre2_3.zip" langages={[]} lienCompetence=" Lié à la competence 3."/>
        <ProjetDetail id="projet-detail-10" title="Projet 4" txt="Pour ce projet réalisé en trinôme, nous sommes partis d'un schéma UML avec comme sujet les différentes formation de Parcoursup. Ce schéma nous a servi de guide pour traduire les différentes tables et relations en SQL. Nous devions ensuite peupler les tables a l'aide d'un fichier CSV contenant toutes les données nécessaire." media="../../sae_204/sae_204.jpg" dlDossier="../../dl/Projet_BUT_semestre1_1.zip" langages={['SQL']} lienCompetence=" Lié à la competence 4."/>
        <ProjetDetail id="projet-detail-11" title="Projet 5" txt="Toujours en trinôme, nous devions réaliser la gestion de notre projet 2.01. Pour ce faire nous sommes passé par plusieurs étapes : la création de la note de cadrage et de la SEL, puis L'organigramme de tâches, la matrice RACI et l'estimation des charges  et pour finir la planification Gantt." media="../../sae_205/sae_205_1.png" dlDossier="../../dl/Projet_BUT_semestre1_1.zip" langages={[]}  lienCompetence=" Lié à la competence 5."/>
        <ProjetDetail id="projet-detail-12" title="Projet 6" txt="Lors de ce projet notre missions était de prévoir une activité de team building pour une entreprise de notre choix. En passant par la réalisation d'un flyer, d'un film évènementiel et la présentation oral de notre journée de team building." media="../../sae_206/sae_206_1.jpg" dlDossier="../../dl/Projet_BUT_semestre2_6.zip" langages={[]} lienCompetence=" Lié à la competence 6."/>
      </div>
      <div id="annee3" className='projets-section'>
        <h1>3ème année</h1>
        <ProjetDetail id="projet-detail-13" title="Projet 1" txt="Dans ce projet, j'avais pour but de réaliser un jeu de Puissance 4 en langage C, qui se joue entièrement dans le terminal en utilisant les touches du clavier. Malgré les difficultés rencontrés en cours de route, j'ai réussi à terminer ce projet avec succès, ce qui m'a permis de consolider mes connaissances en C et de développer mes compétences en développement de jeux." media="../../sae_301/sae_301_3.png" dlDossier="../../dl/Projet_BUT_semestre1_1.zip" langages={['HTML', 'CSS', 'JavaScript', 'PHP', 'SQL']} lienCompetence=" Lié à toutes les competences."/>
      </div>
    </div>
  );
}

export default Projets;
